export const HERO_BG_DELAY=1000
export const HERO_BG_SCALE_OUT_DELAY=HERO_BG_DELAY+100
export const HER_LOADING_BAR_DELAY=0

export const HERO_TITLE_DELAY=HERO_BG_SCALE_OUT_DELAY+500

export const HERO_BOTTOM_DELAY=HERO_TITLE_DELAY

export const HERO_BOTTOM_FIRST_WORD=HERO_BOTTOM_DELAY 
export const HERO_BOTTOM_SECOND_WORD=HERO_BOTTOM_DELAY + 200
export const HERO_BOTTOM_THIRD_WORD=HERO_BOTTOM_SECOND_WORD + 200